In [1]:
import matplotlib.pyplot as plt
import torch
import spatialSSL

file_path = "../example_files/img_119670929_1199650932.h5ad"

# Create the dataloader
dataset_constructor = spatialSSL.Dataloader.EgoNetDatasetConstructor(file_path=file_path, image_col="section",
                                                                     label_col="class_label", include_label=False,
                                                                     radius=20, node_level=3)

# Load the data
dataset_constructor.load_data()

# Construct the graph
#dataset = dataset_constructor.construct_graph()
dataset = torch.load("../dataset/dataset2.pt")

total_cells = len(dataset_constructor.adata)
print(len(dataset), "of", total_cells)

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/2_img_dataset.pt'

In [2]:
# Construct the graph
#dataset = dataset_constructor.construct_graph()
dataset = torch.load("../dataset/dataset2.pt")

total_cells = len(dataset_constructor.adata)
print(len(dataset), "of", total_cells)

52528 of 55530


In [2]:
#torch.save(dataset, "../dataset/dataset2.pt")

In [ ]:
def train_one_epoch(model, optimizer, data_loader, device, training=True):
    model.train(training)
    losses = []
    accuracies = []
    for batch in data_loader:
        optimizer.zero_grad()
        x = batch.x.to(device)
        edge_index = batch.edge_index.to(device)
        y = batch.y.to(device)
        out = model(x, edge_index)
        loss = F.cross_entropy(out, y)
        losses.append(loss.item())
        if training:
            loss.backward()
            optimizer.step()
        acc = (out.argmax(dim=1) == y).sum().item() / len(y)
        accuracies.append(acc)
    return mean(losses), mean(accuracies)

In [3]:
from torch import Tensor, nn
from torch.nn import Linear
from torch_geometric.nn import GCNConv, GATConv

class GCN(nn.Module):
    def __init__(self, in_channels, hidden_channels, num_classes):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.lin11 = nn.Linear(hidden_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.lin2 = nn.Linear(hidden_channels, num_classes)

    def forward(self, x: Tensor, edge_index: Tensor) -> Tensor:
        x = self.conv1(x, edge_index).relu()
        x = self.lin11(x).relu()
        x = self.conv2(x, edge_index).relu()
        x = self.lin2(x).softmax(dim=1)
        return x

In [4]:
net = GCN(in_channels=550, hidden_channels=550, nu=550)

#weigths = torch.load("../models/best_model.pt")

# load model state
#net.load_state_dict(torch.load("../models/best_model.pt"),  strict=False)
#weigths

TypeError: __init__() got an unexpected keyword argument 'out_channels'

In [111]:
weigths

OrderedDict([('conv1.bias',
              tensor([ 1.8485e-01,  5.2149e-02,  2.5553e-01,  1.6856e-01,  2.3748e-01,
                      -3.8776e-02,  1.3727e-01,  2.3419e-01,  1.7705e-01,  2.0290e-01,
                       1.7215e-01,  9.0370e-02,  2.4223e-01,  8.7808e-02,  2.3943e-02,
                       2.1018e-01,  1.6180e-01,  2.3478e-01,  2.4502e-01,  2.8955e-01,
                       1.5057e-01,  1.2783e-01,  2.5978e-01,  1.2592e-01,  2.7632e-01,
                       2.6478e-01, -1.7233e-02,  1.4562e-01,  1.9541e-01,  8.0785e-03,
                       1.6502e-01,  1.5623e-01,  1.5175e-01,  1.0052e-01,  1.9142e-01,
                       5.7890e-02,  1.3251e-01,  1.6412e-01,  6.0202e-02,  1.8642e-01,
                       1.5235e-01,  1.6511e-01,  2.1999e-01,  3.1011e-01,  2.2046e-02,
                       1.9942e-01,  2.5617e-01,  1.4763e-01,  2.0891e-01,  9.1363e-02,
                       1.9775e-01,  1.7344e-01,  1.4490e-01,  1.8761e-01,  1.9027e-01,
               

In [109]:
net.state_dict()

OrderedDict([('conv1.bias',
              tensor([ 1.8485e-01,  5.2149e-02,  2.5553e-01,  1.6856e-01,  2.3748e-01,
                      -3.8776e-02,  1.3727e-01,  2.3419e-01,  1.7705e-01,  2.0290e-01,
                       1.7215e-01,  9.0370e-02,  2.4223e-01,  8.7808e-02,  2.3943e-02,
                       2.1018e-01,  1.6180e-01,  2.3478e-01,  2.4502e-01,  2.8955e-01,
                       1.5057e-01,  1.2783e-01,  2.5978e-01,  1.2592e-01,  2.7632e-01,
                       2.6478e-01, -1.7233e-02,  1.4562e-01,  1.9541e-01,  8.0785e-03,
                       1.6502e-01,  1.5623e-01,  1.5175e-01,  1.0052e-01,  1.9142e-01,
                       5.7890e-02,  1.3251e-01,  1.6412e-01,  6.0202e-02,  1.8642e-01,
                       1.5235e-01,  1.6511e-01,  2.1999e-01,  3.1011e-01,  2.2046e-02,
                       1.9942e-01,  2.5617e-01,  1.4763e-01,  2.0891e-01,  9.1363e-02,
                       1.9775e-01,  1.7344e-01,  1.4490e-01,  1.8761e-01,  1.9027e-01,
               

In [95]:
len(dataset_constructor.adata.obs.class_label.unique())#.cat.codes.values

['MY GABA', 'MY Glut', 'Astro-Epen', 'Oligo', 'P GABA', ..., 'CNU-HYa GABA', 'MB Glut', 'CNU-HYa Glut', 'TH Glut', 'MB Dopa']
Length: 20
Categories (20, object): ['Astro-Epen', 'CB GABA', 'CB Glut', 'CNU-HYa GABA', ..., 'P GABA', 'P Glut', 'TH Glut', 'Vascular']

In [96]:
for batch in dataset:
    print(batch.x)
    break

tensor([    0,  3600, 17561])


In [98]:
for batch in train_loader:
    print(batch.x)
    break

tensor([ 1302,  6712,  6727,  ..., 39346, 40173, 50669])


In [5]:
from tqdm.auto import tqdm
from torch import optim
from statistics import mean
from torcheval.metrics import MulticlassAccuracy


train_loader, val_loader, test_loader = spatialSSL.Utils.split_dataset(dataset=dataset, split_percent=(0.8, 0.1, 0.1), batch_size = 64)

epochs = 20
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

net = GCN(in_channels=550, hidden_channels=550, num_classes=len(dataset_constructor.adata.obs.class_label.unique()))

#net.load_state_dict(torch.load("../models/full_model.pt",  map_location=torch.device(device)), strict=False)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)#, momentum=0.9)




net.to(device)
# Train the model
# training loop
for epoch in tqdm(range(epochs)):
    net.train()


    running_loss = 0.0

    train_acc = MulticlassAccuracy()
    val_acc = MulticlassAccuracy()

    for data in train_loader:
        #inputs, _ = data.
        input = torch.tensor(dataset_constructor.adata.X[data.x].toarray(), dtype=torch.double).to(device).float()

        labels = torch.tensor(dataset_constructor.adata[data.x.numpy()].obs.class_label.cat.codes.values).to(device).long()
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward + backward + optimize
        outputs = net(input, data.edge_index)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Print statistics
        #accuracy = (outputs.argmax(dim=1) == labels).sum().item() / len(labels)
        train_acc.update(outputs.argmax(dim=1), labels)
        #train_accs.append(accuracy)
        running_loss += loss.item()

    running_loss = running_loss / len(train_loader)
       # Validation
    net.eval()
    val_accs = []
    with torch.no_grad():
        val_loss = 0.0
        for data in val_loader:

            input = torch.tensor(dataset_constructor.adata.X[data.x].toarray(), dtype=torch.double).to(device).float()
            labels = torch.tensor(dataset_constructor.adata[data.x.numpy()].obs.class_label.cat.codes.values).to(device).long()
            outputs = net(input, data.edge_index)
            loss = criterion(outputs, labels)

            val_acc.update(outputs.argmax(dim=1), labels)

            #accuracy = (outputs.argmax(dim=1) == labels).sum().item() / len(labels)
            #val_accs.append(accuracy)
            val_loss += loss.item()

        #val_accuracy = 100 * correct / total
        avg_val_loss = val_loss / len(val_loader)



    print(f'Epoch: {epoch+1}/{epochs}, Train Loss: {running_loss:.4f}, Val Loss: {avg_val_loss:.4f} Train Acc: {train_acc.compute():.4f}, Val Acc: {val_acc.compute():.4f}')



    #print(f'Epoch {epoch + 1}, Loss: {running_loss / len(train_loader):.3f}, accuracy: {sum(all_accuracy) / len(all_accuracy):.3f}')

  0%|          | 0/20 [00:00<?, ?it/s]


KeyboardInterrupt



In [7]:
from tqdm.auto import tqdm
from torch import optim
from statistics import mean
from torcheval.metrics import MulticlassAccuracy

epochs = 20
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

net = GCN(in_channels=550, hidden_channels=550, num_classes=len(dataset_constructor.adata.obs.class_label.unique()))

#net.load_state_dict(torch.load("../models/full_model.pt",  map_location=torch.device(device)), strict=False)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.00001)#, momentum=0.9)




net.to(device)
# Train the model
# training loop
for epoch in tqdm(range(epochs)):
    net.train()


    running_loss = 0.0

    train_acc = MulticlassAccuracy()
    val_acc = MulticlassAccuracy()

    for data in train_loader:
        #inputs, _ = data.
        input = torch.tensor(dataset_constructor.adata.X[data.x].toarray(), dtype=torch.double).to(device).float()

        labels = torch.tensor(dataset_constructor.adata[data.x.numpy()].obs.class_label.cat.codes.values).to(device).long()
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward + backward + optimize
        outputs = net(input, data.edge_index)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Print statistics
        #accuracy = (outputs.argmax(dim=1) == labels).sum().item() / len(labels)
        train_acc.update(outputs.argmax(dim=1), labels)
        #train_accs.append(accuracy)
        running_loss += loss.item()

    running_loss = running_loss / len(train_loader)
       # Validation
    net.eval()
    val_accs = []
    with torch.no_grad():
        val_loss = 0.0
        for data in val_loader:

            input = torch.tensor(dataset_constructor.adata.X[data.x].toarray(), dtype=torch.double).to(device).float()
            labels = torch.tensor(dataset_constructor.adata[data.x.numpy()].obs.class_label.cat.codes.values).to(device).long()
            outputs = net(input, data.edge_index)
            loss = criterion(outputs, labels)

            val_acc.update(outputs.argmax(dim=1), labels)

            #accuracy = (outputs.argmax(dim=1) == labels).sum().item() / len(labels)
            #val_accs.append(accuracy)
            val_loss += loss.item()

        #val_accuracy = 100 * correct / total
        avg_val_loss = val_loss / len(val_loader)



    print(f'Epoch: {epoch+1}/{epochs}, Train Loss: {running_loss:.4f}, Val Loss: {avg_val_loss:.4f} Train Acc: {train_acc.compute():.4f}, Val Acc: {val_acc.compute():.4f}')



    #print(f'Epoch {epoch + 1}, Loss: {running_loss / len(train_loader):.3f}, accuracy: {sum(all_accuracy) / len(all_accuracy):.3f}')

  0%|          | 0/20 [00:00<?, ?it/s]

Epoch: 1/20, Train Loss: 2.6104, Val Loss: 2.4669 Train Acc: 0.5257, Val Acc: 0.6286
Epoch: 2/20, Train Loss: 2.4438, Val Loss: 2.4517 Train Acc: 0.6449, Val Acc: 0.6324
Epoch: 3/20, Train Loss: 2.4395, Val Loss: 2.4484 Train Acc: 0.6452, Val Acc: 0.6336
Epoch: 4/20, Train Loss: 2.4346, Val Loss: 2.4379 Train Acc: 0.6492, Val Acc: 0.6473
Epoch: 5/20, Train Loss: 2.4257, Val Loss: 2.4348 Train Acc: 0.6580, Val Acc: 0.6492
Epoch: 6/20, Train Loss: 2.4218, Val Loss: 2.4333 Train Acc: 0.6611, Val Acc: 0.6502
Epoch: 7/20, Train Loss: 2.4218, Val Loss: 2.4320 Train Acc: 0.6603, Val Acc: 0.6511
Epoch: 8/20, Train Loss: 2.4230, Val Loss: 2.4321 Train Acc: 0.6592, Val Acc: 0.6507
Epoch: 9/20, Train Loss: 2.4216, Val Loss: 2.4312 Train Acc: 0.6603, Val Acc: 0.6512
Epoch: 10/20, Train Loss: 2.4202, Val Loss: 2.4310 Train Acc: 0.6620, Val Acc: 0.6512
Epoch: 11/20, Train Loss: 2.4149, Val Loss: 2.4311 Train Acc: 0.6674, Val Acc: 0.6518
Epoch: 12/20, Train Loss: 2.4194, Val Loss: 2.4300 Train Acc: 0


KeyboardInterrupt



In [ ]:
def train_one_epoch(model, optimizer, data_loader, device, training=True):
    model.train(training)
    losses = []
    accuracies = []
    for batch in data_loader:
        optimizer.zero_grad()
        x = batch.x.to(device)
        edge_index = batch.edge_index.to(device)
        y = batch.y.to(device)
        out = model(x, edge_index)
        loss = F.cross_entropy(out, y)
        losses.append(loss.item())
        if training:
            loss.backward()
            optimizer.step()
        acc = (out.argmax(dim=1) == y).sum().item() / len(y)
        accuracies.append(acc)
    return mean(losses), mean(accuracies)